language: python
env:
  global:
  - POSTGRES_PASSWORD=mypassword
  - POSTGRES_USER=mydatabaseuser
python:
  - "3.9"
services:
  - postgresql
install:
  - pip install poetry
script:
  - poetry install
  - poetry run flake8 . --extend-exclude=dist,build,migrations --show-source --statistics
  - poetry run python manage.py test
