language: python
python:
  - "3.9"
services:
  - postgresql
install:
  - pip install poetry
before_script:
  - psql -c "CREATE USER mydatabaseuser WITH PASSWORD 'mypassword';" -U postgres
  - psql -c "ALTER USER mydatabaseuser CREATEDB;" -U postgres
script:
  - poetry install
  - poetry run flake8 . --extend-exclude=dist,build,migrations --show-source --statistics
  - poetry run python manage.py test
