format_version: 10
pipelines:
  django-pipeline:
    group: My-Pipelines
    label_template: ${COUNT}
    lock_behavior: none
    display_order: -1
    materials:
      git-2922648:
        git: https://github.com/danielfs/polls-app
        shallow_clone: false
        auto_update: true
        branch: main
    stages:
    - django-setup:
        fetch_materials: true
        keep_artifacts: false
        clean_workspace: false
        approval:
          type: success
          allow_only_on_success: false
        jobs:
          build-test-lint:
            timeout: 0
            tasks:
            - exec:
                arguments:
                - install
                - poetry
                command: pip
                run_if: passed
            - exec:
                arguments:
                - install
                command: poetry
                run_if: passed
            - exec:
                arguments:
                - run
                - flake8
                - .
                - --extend-exclude=dist,build,migrations
                - --show-source
                - --statistics
                command: poetry
                run_if: passed
            - exec:
                arguments:
                - run
                - python
                - manage.py
                - test
                command: poetry
                run_if: passed
